# @package _global_

defaults:
  - _self_
  - model: rqvae
  - paths: default
  - extras: default
  - hydra: default
  - optional local: default
  - experiment: rqvae_4_levels

item_path: ${paths.data_dir}/processed/rqvae/goodreads.item.json
embedding_path: ${paths.data_dir}/processed/rqvae/goodreads.emb-bge.npy
output_path: ${paths.data_dir}/processed/rqvae/goodreads.index.json
ckpt_path: ckpts/rqvae/epoch_055_full_catalog.ckpt  # TODO
batch_size: 1024
num_workers: 12
pin_memory: False
use_sk_infer: False
compare_sk_assignments: True
stats_output_path: null
health_output_path: null

# other configs
task_name: "rqvae_generate_sid"
tags: ["rqvae", "goodreads", "sid"]
seed: 728
optimized_metric: null
