# @package _global_

defaults:
  - _self_
  - text2emb_default
  - paths: default
  - extras: default
  - hydra: default
  - optional local: default

# text2emb
item_path: ${paths.data_dir}/processed/rqvae/goodreads.item.json
output_path: ${paths.data_dir}/processed/rqvae/goodreads.emb-bge.npy
plm_checkpoint: BAAI/bge-base-en-v1.5
batch_size: 128
max_length: 1024

# other configs
task_name: "rqvae_text2emb"
tags: ["rqvae", "goodreads", "text2emb"]
seed: 728
optimized_metric: null
