# @package _global_

defaults:
  - data: rl
  - model: rl_lora
  - callbacks: rl
  - logger: csv
  - trainer: gpu
  - paths: default
  - extras: default
  - hydra: default
  - optional local: default

  - experiment: null
  - debug: null
  - _self_

trainer:
  max_epochs: 12
  log_every_n_steps: 10
  accumulate_grad_batches: 8

data:
  sft_export_dir: ${paths.data_dir}/ckpts/sft/epoch_4 # TODO
  batch_size: 1
  max_train_samples: null # debug
  max_valid_samples: null # debug

model:
  max_length: 1024
  num_generations: 4
  rank_reward_lambda: 0.1
  use_partial_match_reward: True
  partial_match_lambda: 0.2
  use_long_tail_reward: False
  long_tail_reward_lambda: 0.05
  kl_beta: 0.02
  clip_epsilon: 0.2
  warmup_ratio: 0.03
  attn_implementation: null

task_name: "train_rl"
tags: ["rl", "grpo", "goodreads"]

train: True
test: False
ckpt_path: null

seed: 728
optimized_metric: "val/rule_hit_at_g"
