# @package _global_

defaults:
  - data: rl
  - model: rl_lora
  - callbacks: rl
  - logger: csv
  - trainer: gpu
  - paths: default
  - extras: default
  - hydra: default
  - optional local: default

  - experiment: null
  - debug: null
  - _self_

trainer:
  max_epochs: 1
  log_every_n_steps: 1
  accumulate_grad_batches: 8

data:
  sft_export_dir: ${paths.data_dir}/ckpts/sft/epoch_4 # TODO
  batch_size: 1
  max_train_samples: null # debug
  max_valid_samples: null # debug

model:
  num_generations: 4

task_name: "train_rl"
tags: ["rl", "grpo", "goodreads"]

train: True
test: False
ckpt_path: null

seed: 728
optimized_metric: "val/rule_hit_at_g"
