# @package _global_

defaults:
  - data: sft
  - model: sft_qlora
  - callbacks: sft
  - logger: csv
  - trainer: gpu
  - paths: default
  - extras: default
  - hydra: default
  - optional local: default

  - experiment: null
  - debug: null
  - _self_

trainer:
  max_epochs: 10

data:
  batch_size: 2

task_name: "train_sft"
tags: ["sft", "goodreads"]

train: True
test: False
ckpt_path: null

seed: 728
optimized_metric: "val/loss_recommendation"
